name: Build and Deploy
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate Postgres Client
        run: yarn prisma generate

      - name: Build
        run: yarn build

      - name: Copy required files to output dir
        run: |
          cp package.json dist/
          cp yarn.lock dist/
          cp -r .npmrc dist/

      - name: Create deployment package
        run: (cd dist && zip -r ../deploy.zip .)

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: deploy.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: build

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%Y%m%d%H%M%S)"

      - name: Set deploy target URL
        id: set_target
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "Deploying to production..."
          echo "::set-output name=target_environment::NodeBackend-Prod"
          else
          echo "Deploying to test..."
          echo "::set-output name=target_environment::NodeBackend-Test"
          fi

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: FindsBackend
          environment_name: ${{ steps.set_target.outputs.target_environment }}
          version_label: ${{ steps.timestamp.outputs.timestamp }}
          region: us-east-1
          deployment_package: deploy.zip
          wait_for_deployment: false
